/* COMP508 PART C TASK 5 */ 
/* Mohammed Ismail (1804017) and Letisia Pangata’a (15897475)*/ 

/* SQL Query 1 */ 

SELECT  
CUSTOMER_ID AS "CUSTOMER ID",  
FIRST_NAME || ' ' || LAST_NAME AS "CUSTOMER NAME", 
EMAIL_ADDRESS AS "CUSTOMER EMAIL ADDRESS", 
PHONE_NO AS "CUSTOMER PHONE NUMBER" 
PAYMENT_DETAILS AS "PAYMENT DETAILS" 
FROM  
CUSTOMERS 
WHERE  
CUSTOMER_ID = “&CUSTOMER_ID”; 

/* IF CUSTOMER_ID = 1 */ 

/* SQL Query 2 */ 

SELECT  
CUSTOMER_ORDER_ID AS "CUSTOMER ORDER ID",  
ITEM_DESC AS "ITEM DESCRIPTION", 
COST_OF_PRINTS AS "COST OF PRINTS" 
TOTAL_ORDER_PRICE AS "TOTAL ORDER PRICE" 
FROM  
CUSTOMERS_ORDER 
WHERE  
CUSTOMER_ORDER_ID = “&CUSTOMER_ORDER_ID”; 

/* IF CUSTOMER_ORDER_ID = 1 */ 

/* SQL Query 3 */ 

SELECT  
ORDER_ID AS "ORDER ID",  
DELIVERY_START_DATE AS "DELIVERY DATE", 
STREET_ADDRESS || ', ' || CITY || ', ' || COUNTRY AS "DELIVERY ADDRESS", 
POSTAL_CHARGE AS "POSTAL CHARGE" 
FROM  
DELIVERY 
WHERE  
ORDER_ID = “&ORDER_ID”; 

/* IF ORDER_ID = 1 */

/* SQL Query 4 */ 

SELECT  
LOCATION_ID AS "LOCATION ID",  
LOCATION_ADDRESS AS "LOCATION ADDRESS" 
LOCATION_PRICE AS "LOCATION PRICE" 
FROM  
LOCATIONS 
WHERE  
LOCATION_ID = “&LOCATION_ID”; 

/* IF LOCATION_ID = 1 */ 

/* SQL Query 5 */ 

SELECT  
FK_EMPLOYEE_ID AS "EMPLOYEE ID", 
PHOTO_SESSION_ID AS "PHOTO SESSION ID", 
FK_CUSTOMER_ID AS "CUSTOMER ID", 
AVAILABLE_DATE AS "AVAILABLE DATE", 
PRICE AS "PRICE" 
FROM  
PHOTO_SESSIONS 
WHERE  
PHOTO_SESSION_ID = “&PHOTO_SESSION_ID”; 
 
/* IF PHOTO_SESSION_ID = 1 */ 